name: NBDI Educational Diversity Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nbdi_analysis
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Prepare CSV data file
      run: |
        if [ -f "Stockholm Large – NBDI2025.csv" ]; then
          cp "Stockholm Large – NBDI2025.csv" /tmp/
          echo "CSV file copied successfully"
        else
          echo "Creating sample data for demo"
          cat > "/tmp/Stockholm Large – NBDI2025.csv" << 'EOF'
company,board_or_executive,position,approximate_categorization,special_area,name,nationality,year_of_birth,educational_background,gender,remarks
AAK,Executive Management,CEO,Executive Management,Business,John Smith,Swedish,1970,Business,Male,
AAK,Executive Management,CFO,Executive Management,Finance,Jane Doe,Swedish,1975,"Business, Finance",Female,
AAK,Executive Management,CTO,Executive Management,Technology,Erik Larsson,Swedish,1980,Engineering,Male,
ABB,Executive Management,CEO,Executive Management,Business,Lisa Anderson,Swedish,1965,Law,Female,
ABB,Executive Management,CFO,Executive Management,Finance,Magnus Berg,Swedish,1972,Business,Male,
ABB,Executive Management,COO,Executive Management,Operations,Anna Nilsson,Swedish,1978,Engineering,Female,
Volvo,Executive Management,CEO,Executive Management,Business,Carl Svensson,Swedish,1968,Business,Male,
Volvo,Executive Management,CFO,Executive Management,Finance,Maria Johansson,Swedish,1973,"Business, Law",Female,
Ericsson,Executive Management,CEO,Executive Management,Business,Sofia Lindqvist,Swedish,1971,Engineering,Female,
EOF
        fi

    - name: Run NBDI Analysis
      run: |
        echo "Starting NBDI Educational Diversity Analysis..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\pset border 2" \
          -c "\pset format aligned" \
          -c "\timing on" \
          -f Solution.sql
      env:
        PGPASSWORD: postgres

    - name: Export results using client-side copy
      run: |
        echo "Exporting results..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\copy education_diversity_by_company TO '/tmp/education_diversity_by_company.csv' CSV HEADER"
        
        echo "Results Summary:"
        if [ -f "/tmp/education_diversity_by_company.csv" ]; then
          echo "Results exported successfully"
          echo "Companies analyzed: $(tail -n +2 /tmp/education_diversity_by_company.csv | wc -l)"
          cat /tmp/education_diversity_by_company.csv
        fi
      env:
        PGPASSWORD: postgres

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nbdi-analysis-results
        path: /tmp/education_diversity_by_company.csv
        retention-days: 30

    - name: Display summary
      run: |
        echo "=== ANALYSIS SUMMARY ==="
        if [ -f "/tmp/education_diversity_by_company.csv" ]; then
          echo "Analysis completed successfully"
          echo "Results saved to: education_diversity_by_company.csv"
          echo "Total companies analyzed: $(tail -n +2 /tmp/education_diversity_by_company.csv | wc -l)"
          echo "Download results from the 'Artifacts' section"
        else
          echo "Analysis failed - no output file generated"
        fi