name: NBDI Educational Diversity Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nbdi_analysis
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --mount type=bind,source=/tmp,target=/tmp

        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Prepare CSV data file
      run: |
        # Create temp directory and copy CSV
        sudo mkdir -p /tmp
        if [ -f "Stockholm Large – NBDI2025.csv" ]; then
          sudo cp "Stockholm Large – NBDI2025.csv" /tmp/
          sudo chmod 644 "/tmp/Stockholm Large – NBDI2025.csv"
          echo "CSV file copied successfully"
        else
          echo "CSV file not found, creating sample data for demo"
          # Create a minimal sample CSV for testing
          echo "company,board_or_executive,position,approximate_categorization,special_area,name,nationality,year_of_birth,educational_background,gender,remarks" > /tmp/sample.csv
          echo "TestCorp,Executive Management,CEO,,Business,John Doe,Swedish,1970,Business,Male," >> /tmp/sample.csv
          sudo mv /tmp/sample.csv "/tmp/Stockholm Large – NBDI2025.csv"
        fi

    - name: Run NBDI Analysis
      run: |
        echo "Starting NBDI Educational Diversity Analysis..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\pset border 2" \
          -c "\pset format aligned" \
          -c "\timing on" \
          -f Solution.sql
      env:
        PGPASSWORD: postgres

    - name: Export and display results
      run: |
        echo "Exporting results..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\copy education_diversity_by_company TO '/tmp/education_diversity_by_company.csv' CSV HEADER"
        
        echo "Results exported. Sample output:"
        head -10 /tmp/education_diversity_by_company.csv
      env:
        PGPASSWORD: postgres

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: nbdi-analysis-results
        path: |
          /tmp/education_diversity_by_company.csv
        retention-days: 30  # Keep artifacts for 30 days

    - name: Display summary
      run: |
        echo "=== ANALYSIS SUMMARY ==="
        if [ -f "/tmp/education_diversity_by_company.csv" ]; then
          echo "Analysis completed successfully"
          echo " Results saved to: education_diversity_by_company.csv"
          echo " Total companies analyzed: $(tail -n +2 /tmp/education_diversity_by_company.csv | wc -l)"
          echo " Download results from the 'Artifacts' section below"
        else
          echo " Analysis failed - no output file generated"
        fi