name: NBDI Educational Diversity Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nbdi_analysis
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Prepare CSV data file
      run: |
        if [ -f "Stockholm Large – NBDI2025.csv" ]; then
          cp "Stockholm Large – NBDI2025.csv" /tmp/
          echo "CSV file copied successfully"
        fi
    - name: Run NBDI Analysis
      run: |
        echo "Starting NBDI Educational Diversity Analysis..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\pset border 2" \
          -c "\pset format aligned" \
          -c "\timing on" \
          -f Solution.sql
      env:
        PGPASSWORD: postgres

    - name: Export results using client-side copy
      run: |
        echo "Exporting results..."
        PGPASSWORD=postgres psql -h localhost -U postgres -d nbdi_analysis \
          -c "\copy education_diversity_by_company TO '/tmp/education_diversity_by_company.csv' CSV HEADER"
        
        echo "Results Summary:"
        if [ -f "/tmp/education_diversity_by_company.csv" ]; then
          echo "Results exported successfully"
          echo "Companies analyzed: $(tail -n +2 /tmp/education_diversity_by_company.csv | wc -l)"
          cat /tmp/education_diversity_by_company.csv
        fi
      env:
        PGPASSWORD: postgres

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nbdi-analysis-results
        path: /tmp/education_diversity_by_company.csv
        retention-days: 30

    - name: Display summary
      run: |
        echo "=== ANALYSIS SUMMARY ==="
        if [ -f "/tmp/education_diversity_by_company.csv" ]; then
          echo "Analysis completed successfully"
          echo "Results saved to: education_diversity_by_company.csv"
          echo "Total companies analyzed: $(tail -n +2 /tmp/education_diversity_by_company.csv | wc -l)"
          echo "Download results from the 'Artifacts' section"
        else
          echo "Analysis failed - no output file generated"
        fi